language: go
before_install:
- pushd $HOME
- wget -q https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-1.9.17.zip
- unzip -q go_appengine_sdk_linux_amd64-1.9.17.zip
- cd go_appengine
- export GAE=$(pwd)
- popd
- npm install -g grunt-cli
- git clone git://github.com/n1k0/casperjs.git ~/casperjs
- cd ~/casperjs
- git checkout tags/1.1-beta3
- export PATH=$PATH:`pwd`/bin
- cd -
install:
- cd $TRAVIS_BUILD_DIR
- export GOPATH=$TRAVIS_BUILD_DIR
- export GOHOME=$GAE
- export PATH=$GAE:$PATH
- which go
- go env
- chmod +x ./ciscripts/goget.sh
- ./ciscripts/goget.sh
before_script:
- goapp serve &
- sleep 5
script:
- casperjs --pre=caspertests/helpers/adminlogin.coffee test caspertests/tests
after_success:
- python $GAE/appcfg.py update . --oauth2_refresh_token=$GAE_OAUTH -A dev-slacktools
after_script:
- casperjs --pre=caspertests/helpers/adminlogin.coffee test caspertests/tests --env=gaedev --user_id=$GAE_TEST_USER --user_password=$GAE_TEST_USER_PASSWORD
env:
  global:
  - secure: KiEdocf9yqxGaBaMO+5YwfrHWKEMIkqSZx40uOenLCJWvQbm+KRlvTjqyGR/SxJDqjYwS82LAdMILqhzVSjdhPgyJSSzMXXL/YkKccedkZJabHu6FXXwlkSRyxIyr1JRqeSzzSQHtYb8VqtKQ8GwqBeWcS9mZtT5Fhxx+WcH6QQ=
  - secure: nksf9ORgB4yMnjf9qHbH0IfGgj9J4Nsk1bwArTMLDyxSDIduEg7p80HXPqD0K9KTrfshs8HqouYDz8T5z9wORn8sKLA/2c9I/CXl5H1Rh5CZY3V8Ai4jo2VDudvrtM8pfKoOFB3psWJVxAAfAp6PMYcVZ8uYb07HrK18CFL5Pvs=
  - secure: IJvZ47LmYAxck5iqWaz7xhIt9Adj/Zq+jN/W86n+a5Fi7XRs6ZHSif1ZRrCacOT272//gHieG3ItCWS44i8e8bo1l/H9Vkp71juRinLD4fOE9LLboV4xtKfX7GOJcTM1vQTp0eKoZsvT6eRY7kSvEBZ84+tdkj2xnNYNFfQMMM8=
