language: go
before_install:
- pushd $HOME
- mkdir go
- export GOPATH=$HOME/go
- python ciscripts/getlatestsdk.py
- unzip -q go_appengine_sdk_linux_amd64-latest.zip
- cd go_appengine
- export GAE=$(pwd)
- popd
- npm install -g grunt-cli
- git clone git://github.com/n1k0/casperjs.git ~/casperjs
- cd ~/casperjs
- git checkout tags/1.1-beta3
- export PATH=$PATH:`pwd`/bin
- cd -
install:
- cd $TRAVIS_BUILD_DIR
- export PATH=$GAE:$PATH
- export GOROOT=`go env GOROOT`
- export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
- which go
- go env
- chmod +x ./ciscripts/goget.sh
- ./ciscripts/goget.sh
before_script:
- goapp serve &
- sleep 5
script:
- casperjs --pre=caspertests/helpers/adminlogin.coffee test caspertests/tests
