application: goisky-tools
version: 1
runtime: go
api_version: go1

handlers:
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
  mime_type: image/x-icon

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /media
  static_dir: media

- url: /admin/.*
  script: _go_app 
  login: admin
  secure: always

- url: /.*
  script: _go_app
  secure: always

skip_files: |
  ^(.*/)?(
  (casptertests/.*)|
  (node_modules/.*)|
  (testdata/.*)|
  (app\.yaml)|
  (app\.yml)|
  (index\.yaml)|
  (index\.yml)|
  (#.*#)|
  (.*~)|
  (.*DS_Store)|
  (\.gitignore)|
  (README\.md)|
  (LICENSE)|
  )$
